apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
    - name: bootstrap
      port: 9092
      protocol: TCP
    - name: metrics
      port: 5556
  clusterIP: None
  selector:
    app: kafka

