---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: default
spec:
  selector:
    matchLabels:
      app: schema-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry
        component: schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: kafka-service:9092
        image: confluentinc/cp-schema-registry:7.0.1
        name: schema-registry
      restartPolicy: Always
