---
- name: Gather some facts about the control node
  tags: [ create ]
  block:
    - name: Get control node IPv6 address
      ansible.builtin.shell:
        cmd: ip -6 -br addr show dev br0 scope global | awk '{print $3}' | cut -d/ -f1
      register: control_node_ipv6

    - name: Get control node IPv4 address
      ansible.builtin.shell:
        cmd: ip -4 -br addr show dev br0 scope global | awk '{print $3}' | cut -d/ -f1
      register: control_node_ipv4

    - name: Get control node's IPv6 default route
      command: ip -6 route show default
      register: control_ipv6_default_route_with_via

    - name: Debug control node IPv6 address
      debug:
        var: control_node_ipv6.stdout

    - name: Extract control node's IPv6 default route
      set_fact:
        control_ipv6_default_route: "{{ control_ipv6_default_route_with_via.stdout.split(' ')[2] }}"
      when: control_ipv6_default_route_with_via.stdout != ""

    - name: Debug control node's IPv6 default route
      debug:
        var: control_ipv6_default_route

- name: Install K3S and setup kubeconfig
  tags: [ create ]
  block:
    - name: Install k3s on controller
      environment:
        #        INSTALL_K3S_EXEC: --disable=traefik,local-storage --disable-network-policy --data-dir=/tmp/k3s  --cluster-cidr=10.42.0.0/16,2001:cafe:42::/56 --service-cidr=10.43.0.0/16,2001:cafe:43::/112 --node-ip={{ control_node_ipv4.stdout }},{{ control_node_ipv6.stdout }}
        #        INSTALL_K3S_EXEC: --disable=traefik,local-storage --flannel-backend=none --disable-network-policy --data-dir=/tmp/k3s  --cluster-cidr=2001:cafe:42::/56,10.42.0.0/16 --service-cidr=2001:cafe:43::/112,10.43.0.0/16 --node-ip={{ control_node_ipv6.stdout }},{{ control_node_ipv4.stdout }} --node-external-ip={{ control_node_ipv6.stdout }}
        #        INSTALL_K3S_EXEC: --disable=traefik,local-storage --flannel-backend=host-gw --flannel-ipv6-masq=true --data-dir=/tmp/k3s  --cluster-cidr=2001:cafe:42::/56,10.42.0.0/16 --service-cidr=2001:cafe:43::/112,10.43.0.0/16  --node-ip={{ control_node_ipv6.stdout }},{{ control_node_ipv4.stdout }} --node-external-ip={{ control_node_ipv6.stdout }}
        INSTALL_K3S_EXEC: --prefer-bundled-bin  --disable=traefik,local-storage --flannel-backend=host-gw --flannel-ipv6-masq=true --data-dir=/tmp/k3s  --cluster-cidr=2001:cafe:42::/56 --service-cidr=2001:cafe:43::/112  --node-ip={{ control_node_ipv6.stdout }} --node-external-ip={{ control_node_ipv6.stdout }}
        INSTALL_K3S_VERSION: v1.31.0+k3s1
      shell:
        cmd: "curl -sfL https://get.k3s.io | sh -s -"

    - name: Fix server address on control node with api_endpoint
      ansible.builtin.shell:
        kubectl config set-cluster default --server=https://{{ control_node_ipv4.stdout }}:6443

    - name: Get kubeconfig from controller
      ansible.builtin.shell:
        cmd: cat /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_content

    - name: Get kubeconfig path
      set_fact:
        kubeconfig_path: "{{ lookup('env', 'KUBECONFIG') }}"

    - name: Save kubeconfig to localhost
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ kubeconfig_content.stdout }}"
        dest: "{{ kubeconfig_path }}"
        mode: '644'

    - name: Wait for k3s to be ready
      ansible.builtin.wait_for:
        host: "{{ control_node_ipv4.stdout }}"
        port: 6443
        delay: 5
        timeout: 300

    - name: Check if we still have a default route for IPv6
      command: ip -6 route show default
      register: control_ipv6_default_route_check

    - name: Quickfix default route for IPv6
      ansible.builtin.shell:
        cmd: ip -6 route add default via {{ control_ipv6_default_route }} dev br0
      when: control_ipv6_default_route_check.stdout == ""

#    - name: Deploy calico from file
#      delegate_to: localhost
#      kubernetes.core.k8s:
#        kubeconfig: "{{ kubeconfig_path }}"
#        state: present
#        definition: "{{ lookup('ansible.builtin.file', 'calico.yaml') | from_yaml_all }}"

- name: Uninstall k3s server
  tags: [ delete ]
  shell:
    cmd: "/usr/local/bin/k3s-uninstall.sh"
