---
# Setup NFS
- name: Setup NFS
  delegate_to: localhost
  tags: [ always ]
  block:
    - name: Deploy NFS Storage provisioner
      delegate_to: localhost
      kubernetes.core.helm:
        name: csi-driver-nfs
        chart_ref: "csi-driver-nfs"
        chart_version: 4.1.0
        chart_repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
        release_namespace: csi-driver-nfs
        create_namespace: true
      register: csi_driver

    - name: Deploy NFS Storage Class Manifest
      delegate_to: localhost
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'nfs-sc.yaml.j2') | from_yaml }}"