---
# Setup PVC
- name: Setting up PrivateVolumeClaims - Creation block
  tags: [ create ]
  delegate_to: localhost
  block:
    - name: Deploy NFS Storage Class Manifest
      kubernetes.core.k8s:
        state: present
        definition: "{ { lookup('ansible.builtin.template', 'nfs-sc.yaml.j2') | from_yaml } }"

    - name: Deploy PVC for Grafana
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'pvc/grafana-pvc.yaml.j2') | from_yaml }}"

    - name: Deploy PVC for VictoriaMetrics
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'pvc/vm-pvc.yaml.j2') | from_yaml }}"

    - name: Deploy PVC for Flink checkpoints
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'pvc/checkpoint-pvc.yaml.j2') | from_yaml }}"

    - name: Deploy PVC for .jar artifacts
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'pvc/artifacts-pvc.yaml.j2') | from_yaml }}"

- name: Setting up PrivateVolumeClaims - Deletion block
  tags: [ delete ]
  delegate_to: localhost
  block:
    - name: Deploy NFS Storage Class Manifest
      kubernetes.core.k8s:
        state: absent
        definition: "{ { lookup('ansible.builtin.template', 'nfs-sc.yaml.j2') | from_yaml } }"

    - name: Deploy PVC for Grafana
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'pvc/grafana-pvc.yaml.j2') | from_yaml }}"

    - name: Deploy PVC for VictoriaMetrics
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'pvc/vm-pvc.yaml.j2') | from_yaml }}"

    - name: Deploy PVC for Flink checkpoints
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'pvc/checkpoint-pvc.yaml.j2') | from_yaml }}"

    - name: Deploy PVC for .jar artifacts
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'pvc/artifacts-pvc.yaml.j2') | from_yaml }}"