---
- name: Deploy Flink
  tags:
    - create
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
  with_fileglob:
    - "../templates/*.yaml"

- name: Delete Flink
  tags:
    - delete
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
  with_fileglob:
    - "../templates/*.yaml"
