- name: Check if k3s is installed and uninstall it
  tags: [ create ]
  block :
    - name: Check if k3s is installed
      ansible.builtin.stat:
        path: /usr/local/bin/k3s
      register: k3s_installed

    - name: If installed, uninstall k3s
      ansible.builtin.shell:
        cmd: "/usr/local/bin/k3s-agent-uninstall.sh"
      when: k3s_installed.stat.exists

    - name: Reboot the node
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for k3s uninstallation"
        test_command: uptime
      when: k3s_installed.stat.exists
