---
- name: Common setup for all nodes
  tags: [ create ]
  block:
    - name: Create tmp folder for experiment data
      ansible.builtin.file:
        path: /tmp/experiment-data/
        state: directory
        mode: "0777"

#- include_tasks: docker.yaml