- name: Deploy Chaos Mesh
  tags: [ create ]
  block:
    - name: Create a Chaos Mesh namespace
      kubernetes.core.k8s:
        name: chaos-mesh
        kind: Namespace
        state: present
    - name: Add Chaos Mesh repo
      kubernetes.core.helm_repository:
        name: chaos-mesh
        repo_url: https://charts.chaos-mesh.org
    - name: Install Chaos Mesh depending on environment
      kubernetes.core.helm:
        chart_ref: "chaos-mesh/chaos-mesh"
        release_namespace: chaos-mesh
        create_namespace: true
        release_name: chaos-mesh
        release_state: present
        values:
          dashboard:
            ingress:
              enabled: true
              ingressClassName: nginx
              hosts:
                - host:
                  name: chaos-mesh.scalehub.local
                  paths:
                    - /
              pathType: Prefix
            securityMode: false
            nodeSelector:
              node-role.kubernetes.io/control-plane: "true"
          chaosDaemon:
            runtime: containerd
            socketPath: /run/k3s/containerd/containerd.sock
            nodeSelector:
              node-role.kubernetes.io/worker: "consumer"
          controllerManager:
            nodeSelector:
              node-role.kubernetes.io/control-plane: "true"
#        set_values:
#          - value: chaosDaemon.runtime=containerd
#          - value: chaosDaemon.socketPath=/run/k3s/containerd/containerd.sock
#            when: kubernetes_type == "k3s"
#          - value:  chaosDaemon.socketPath=/var/snap/microk8s/common/run/containerd.sock
#            when: kubernetes_type == "microk8s"
    - name: Deploy cluster account for chaos-mesh
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'chaos-mesh-rbac.yaml') | from_yaml_all }}"


- name: Delete Chaos Mesh
  tags: [ delete ]
  block:
    - name : Remove cluster account
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'chaos-mesh-rbac.yaml') | from_yaml_all }}"
    - name : Remove helm chart
      kubernetes.core.helm:
        chart_ref: "chaos-mesh/chaos-mesh"
        release_name: chaos-mesh
        release_namespace: chaos-mesh
        release_state: absent
    - name: Remove namespace
      kubernetes.core.k8s:
        name: chaos-mesh
        kind: Namespace
        state: absent