---
- name: Retrieve values from scalehub configuration file
  tags: [ always ]
  block:
    - name: Get content of shub_config and read it as json
      set_fact:
        shub_config_content: "{{ shub_config | from_json }}"
    - name: Extract chaos vars
      set_fact:
        latency : "{{shub_config_content['experiment.chaos.latency']}}"
        jitter : "{{shub_config_content['experiment.chaos.jitter']}}"
        correlation : "{{shub_config_content['experiment.chaos.correlation']}}"
- import_tasks: install.yaml

- import_tasks: run.yaml
  tags: [ experiment ]
  when: run_experiment | default(false)

- import_tasks: delete.yaml
  tags: [ experiment ]
  when: delete_experiment | default(false)
