---
- name: Retrieve values from scalehub configuration file
  tags: [ always ]
  block:
    - name: Set path to configuration file
      set_fact:
        config_path: "{{ lookup('env','SHUB_CONFIG') }}"
    - name: Read configuration file from SHUB_CONFIG path
      set_fact:
        config_content: "{{ lookup('file', config_path) }}"
    - name: Extract chaos vars
      set_fact:
        latency: "{{ config_content | regex_findall('chaos.delay.latency = (\\d+)') | first }}"
        jitter: "{{ config_content | regex_findall('chaos.delay.jitter = (\\d+)') | first }}"
        correlation: "{{ config_content | regex_findall('chaos.delay.correlation = (\\d+)') | first }}"
- import_tasks: install.yaml

- import_tasks: run.yaml
  tags: [ experiment ]
  when: run_experiment | default(false)

- import_tasks: delete.yaml
  tags: [ experiment ]
  when: delete_experiment | default(false)
