---
# vim: set ft=yaml:
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vm-pvc
  namespace: default
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
