version: "3.6"

secrets:
  g5k_creds:
    # Fill this file with personal Grid5000 credentials
    file: secrets/Grid5000_creds.yaml
  fit_creds:
    # Fill this file with personal FIT credentials
    file: secrets/iotlab_creds.yaml
  # Setup correct path for grid5000 private key in `source` field
  ssh_key:
    file: secrets/grid5000.pk
  grid_pub:
    file: secrets/grid5000.pub


networks:
  scalehub_net:

services:
  scalehub:
    container_name: scalehub
    depends_on:
      - vpn
    # Use network stack from vpn service
    network_mode: service:vpn
    secrets:
      - source: g5k_creds
        target: .python-grid5000.yaml
      - source: fit_creds
        target: .iotlabrc
      - source: ssh_key
        target: id_rsa
      - source: grid_pub
        target: id_rsa.pub
    build:
      context: ${SCALEHUB_BASEDIR}/setup/shub
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - USER=${USER}
    # Source paths refer to scalehub root path
    volumes:
      - type: bind
        source: ${SCALEHUB_BASEDIR}/conf
        target: /app/conf
      - type: bind
        source: ${SCALEHUB_BASEDIR}/playbooks
        target: /app/playbooks
      - type: bind
        source: ${SCALEHUB_BASEDIR}/scripts
        target: /app/scripts
      - type: bind
        source: ${SCALEHUB_BASEDIR}/experiments-data
        target: /app/experiments-data
      - type: bind
        source: ${SCALEHUB_BASEDIR}/info
        target: /app/info
      - type: bind
        source: $SSH_AUTH_SOCK
        target: /ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
  # OpenVPN client service to connect to Grid5000
  vpn:
    build:
      context: ${SCALEHUB_BASEDIR}/setup/vpn
      dockerfile: Dockerfile
    # cap_add, security_opt, and volume required for the image to function
    hostname: scalehub
    cap_add:
      - NET_ADMIN
    extra_hosts:
      # Initialize ingreess.scalehub.local in /etc/hosts with dummy IP
      - "ingress.scalehub.local:127.0.0.1"
    networks:
      - scalehub_net
    ports:
      - "80:80"
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./secrets:/vpn
    environment:
      - DNS
      - TZ=Europe/Paris
    command:
      - -D
    # Option description of -D : Don't use the connection as the default route -> don't break ssh connections from scalehub to g5k
#  # Default production-like vault service for secrets management
#  vault:
#    image: hashicorp/vault
#    container_name: vault
#    hostname: vault
#    command: server -config=/vault/config/vault.json
#    networks:
#        - scalehub_net
#    cap_add:
#      - IPC_LOCK
#    ports:
#      - "8200:8200"
#    volumes:
#      - ./secrets/vault/file:/vault/file
#      - ./secrets/vault/config:/vault/config/
#    environment:
#      - VAULT_ADDR=http://0.0.0.0:8200
#      - VAULT_API_ADDR=http://0.0.0.0:8200
#      - VAULT_CLUSTER_ADDR=http://0.0.0.0:8201
#    secrets:
#      - source: vault_token
#        target: .vault-token