apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: serf-network
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "mode": "bridge",
          "ipam": {
            "type": "whereabouts",
             "range": "10.10.0.0/24"
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning",
          "allmulti": true
        }
      ]
    }'