---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: 39.9.0
    chart: kube-prometheus-stack-39.9.0
    release: prometheus
    role: record-rules
  name: flink-rules
  namespace: monitoring
spec:
  groups:
    - name: flink.rules
      interval: 5s
      rules:
        - record: flink_operator_TumblingEventTimeWindows_throughput_out
          expr: sum by(task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~".*TumblingEventTimeWindows.*"})
        - record: flink_operator_TumblingEventTimeWindows_throughput_in
          expr: sum by(task_name) (flink_taskmanager_job_task_numRecordsInPerSecond{task_name=~".*TumblingEventTimeWindows.*"})
        - record: flink_operator_TumblingEventTimeWindows_parallelism
          expr: sum by(task_name) (count_values by() ("subtask_index", flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~".*TumblingEventTimeWindows.*"}))
        - record: flink_operator_Map_throughput_out
          expr: sum by(task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~"Map"})
        - record: flink_operator_Map_throughput_in
          expr: sum by(task_name) (flink_taskmanager_job_task_numRecordsInPerSecond{task_name=~"Map"})
        - record: flink_operator_Map_parallelism
          expr: sum by(task_name) (count_values by() ("subtask_index", flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~"Map"}))
