---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: 39.9.0
    chart: kube-prometheus-stack-39.9.0
    release: prometheus
    role: record-rules
  name: flink-rules
  namespace: monitoring
spec:
  groups:
    - name: flink.rules
      rules:
        - record: flink_job_operator_throughput_TumblingEventTimeWindows
          expr: sum by(task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~"TumblingEventTimeWindows"})
        - record: flink_job_operator_parallelism_TumblingEventTimeWindows
          expr: sum by(task_name) (count_values by() ("subtask_index", flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~"TumblingEventTimeWindows"}))
        - record: flink_job_operator_throughput_Map
          expr: sum by(task_name) (flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~"Map"})
        - record: flink_job_operator_parallelism_Map
          expr: sum by(task_name) (count_values by() ("subtask_index", flink_taskmanager_job_task_numRecordsOutPerSecond{task_name=~"Map"}))
