---
- name: Retrieve values from scalehub configuration file
  tags: [ always ]
  block:
    - name: Get content of shub_config and read it as json
      set_fact:
        shub_config_content: "{{ shub_config | from_json }}"
    - name: Extract checkpoint_interval and window_size from shub_config
      set_fact:
        partitions: "{{shub_config_content['experiment.kafka_partitions']}}"

- name: Deploy Kafka stack
  tags: [ create ]
  block:
    - name: Deploy Schema-registry service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'schema-registry/schema-registry-service.yaml' ) | from_yaml }}"

    - name: Deploy Zookeper service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'zookeeper/zookeeper-service.yaml' ) | from_yaml }}"

    - name: Deploy Kafka services
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', item) | from_yaml }}"
      with_fileglob: [ "kafka/*.yaml" ]

    - name: Deploy Schema-registry
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'schema-registry/schema-registry-deployment.yaml.j2') | from_yaml }}"

    - name: Deploy Zookeeper
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'zookeeper/zookeeper-deployment.yaml.j2' ) | from_yaml }}"

    - name: Deploy Kafka
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'kafka/kafka-deployment.yaml.j2' ) | from_yaml }}"
        wait: yes

    - name: Deploy Redis service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'redis/redis-service.yaml' ) | from_yaml }}"

    - name: Deploy Redis
      kubernetes.core.k8s:
          state: present
          definition: "{{ lookup('ansible.builtin.template', 'redis/redis-deployment.yaml.j2' ) | from_yaml }}"

- name: Delete Kafka stack
  tags: [ delete ]
  block:
    - name: Delete Schema-registry service
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'schema-registry/schema-registry-service.yaml' ) | from_yaml }}"

    - name: Delete Zookeper service
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'zookeeper/zookeeper-service.yaml' ) | from_yaml }}"

    - name: Delete Kafka services
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', item) | from_yaml }}"
      with_fileglob: [ "kafka/*.yaml" ]

    - name: Delete Schema-registry
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'schema-registry/schema-registry-deployment.yaml.j2') | from_yaml }}"

    - name: Delete Zookeeper
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'zookeeper/zookeeper-deployment.yaml.j2' ) | from_yaml }}"

    - name: Delete Kafka
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'kafka/kafka-deployment.yaml.j2' ) | from_yaml }}"

    - name: Delete Redis service
      kubernetes.core.k8s:
          state: absent
          definition: "{{ lookup('ansible.builtin.file', 'redis/redis-service.yaml' ) | from_yaml }}"

    - name: Delete Redis
      kubernetes.core.k8s:
          state: absent
          definition: "{{ lookup('ansible.builtin.template', 'redis/redis-deployment.yaml.j2' ) | from_yaml }}"

