---
- name: Deploy experiment-monitor
  tags: [ create ]
  block:
    - name: Create service account for experiment-monitor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiment-monitor-role.yaml') | from_yaml_all }}"
    - name: Create PVC for experiment-monitor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiments-pvc.yaml') | from_yaml }}"
    - name: Deploy configmaps for mqtt-broker
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/mqtt-configmaps.yaml') | from_yaml }}"
    - name: Deploy mqtt-broker
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/mqtt-broker.yaml') | from_yaml_all }}"
    - name: Deploy experiment-monitor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiment-monitor-deployment.yaml') | from_yaml }}"
- name: Delete experiment-monitor
  tags: [ delete ]
  block:
    - name: Delete experiment-monitor
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiment-monitor-deployment.yaml') | from_yaml }}"
    - name: Delete mqtt-broker
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/mqtt-broker.yaml') | from_yaml_all }}"
    - name: Delete configmaps for mqtt-broker
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/mqtt-configmaps.yaml') | from_yaml }}"
    - name: Delete ServiceAccount for experiment-monitor
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiment-monitor-role.yaml') | from_yaml_all }}"
