# Setup task for Kubernetes dashboard
---
- name: Setup Kubernetes dashboard
  delegate_to: localhost
  tags: [ create ]
  block:
    - name: Add Kubernetes dashboard repo
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard
        state: present
    - name: Deploy latest version of Kubernetes dashboard
      kubernetes.core.helm:
        chart_ref: "kubernetes-dashboard/kubernetes-dashboard"
        chart_version: 6.0.8
        release_namespace: kubernetes-dashboard
        create_namespace: true
        release_name: kubernetes-dashboard
        release_state: present
        wait: true
        values:
            app:
              settings:
                global:
                  cluster-name: "Scalehub cluster"
                  itemsPerPage: 20
            ingress:
              enabled: true
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/rewrite-target: /
              hosts:
                - kubernetes-dashboard.scalehub.local
              pathType: Prefix
            nodeSelector:
              node-role.kubernetes.io/control-plane: "true"
            nginx:
              enabled: false
            cert-manager:
              enabled: false
    - name: Deploy account setup for dashboard
      kubernetes.core.k8s:
          state: present
          definition: "{{ lookup('ansible.builtin.file', 'kubernetes-dashboard-setup.yaml') | from_yaml_all }}"
- name: Setup Kubernetes dashboard - Deletion block
  delegate_to: localhost
  tags: [ delete ]
  block:
      - name: Delete Kubernetes dashboard
        kubernetes.core.helm:
            chart_ref: "kubernetes-dashboard/kubernetes-dashboard"
            release_namespace: kubernetes-dashboard
            release_name: kubernetes-dashboard
            release_state: absent
