# Setup task for Kubernetes dashboard
---
- name: Setup Kubernetes dashboard
  tags: [ create ]
  block:
    - name: Add Kubernetes dashboard repo
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard
        state: present
    - name: Deploy latest version of Kubernetes dashboard
      kubernetes.core.helm:
        chart_ref: "kubernetes-dashboard/kubernetes-dashboard"
        chart_version: 6.0.8
        release_namespace: kubernetes-dashboard
        create_namespace: true
        release_name: kubernetes-dashboard
        release_state: present
        wait: true
        values: "{{ lookup('ansible.builtin.file', 'kube-dash/values.yaml') | from_yaml }}"

    - name: Deploy account setup for dashboard
      kubernetes.core.k8s:
          state: present
          definition: "{{ lookup('ansible.builtin.file', 'kube-dash/kubernetes-dashboard-setup.yaml') | from_yaml_all }}"

    - name: Deploy Kubernetes dashboard Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'kube-dash/ingress.yaml') | from_yaml }}"

- name: Setup Kubernetes dashboard - Deletion block
  tags: [ delete ]
  block:
    - name: Delete Kubernetes dashboard
      kubernetes.core.helm:
        chart_ref: "kubernetes-dashboard/kubernetes-dashboard"
        release_namespace: kubernetes-dashboard
        release_name: kubernetes-dashboard
        release_state: absent

    - name: Delete Kubernetes dashboard Ingress
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'kube-dash/ingress.yaml') | from_yaml }}"
