# Setup task for Prometheus
- name: Setup Prometheus - Creation block
  tags: [ create ]
  block:
    - name: Deploy latest version of Prometheus Stack in monitoring namespace
      kubernetes.core.helm:
        chart_ref: "kube-prometheus-stack"
        chart_version: 62.3.1
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        release_namespace: monitoring
        create_namespace: true
        release_name: prometheus
        release_state: present
        wait: true
        values: "{{ lookup('ansible.builtin.file', 'prometheus/values.yaml') | from_yaml }}"

    - name: Deploying Flink rules
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'prometheus/rules/flink.yaml') | from_yaml }}"

    - name: Deploying Service Monitors
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', item) | from_yaml }}"
      with_fileglob: [ "prometheus/sm/*.yaml" ]

    - name: Deploy Grafana Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'prometheus/grafana/ingress.yaml') | from_yaml }}"

    - name: Deploy Prometheus Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'prometheus/ingress.yaml') | from_yaml }}"
- name: Setup Prometheus - Deletion block
  tags: [ delete ]
  block:
    - name: Delete Prometheus chart
      kubernetes.core.helm:
        chart_ref: "kube-prometheus-stack"
        chart_version: 62.3.1
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        release_namespace: monitoring
        create_namespace: true
        release_name: prometheus
        release_state: absent

    - name: Delete Flink rules
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'prometheus/rules/flink.yaml') | from_yaml }}"

    - name: Delete Service Monitors
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', item) | from_yaml }}"
      with_fileglob: [ "prometheus/sm/*.yaml" ]

    - name: Delete Grafana Ingress
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'prometheus/grafana/ingress.yaml') | from_yaml }}"

    - name: Delete Prometheus Ingress
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'prometheus/ingress.yaml') | from_yaml }}"