---
# Setup task for VictoriaMetrics database
- name: Setup VM - Creation block
  tags: [ create ]
  block:
    - name: Add VictoriaMetrics repo
      kubernetes.core.helm_repository:
        name: victoria-metrics
        repo_url: https://victoriametrics.github.io/helm-charts/
        state: present
    - name: Deploy latest version of VictoriaMetrics chart for long term storage of experiment results
      kubernetes.core.helm:
        name: victoria-metrics-single
        chart_ref: "victoria-metrics-single"
        chart_version: 0.9.22
        chart_repo_url: https://victoriametrics.github.io/helm-charts/
        release_namespace: default
        # Supply custom values for chart to fix issues with IPv6
        values: "{{ lookup('ansible.builtin.file', 'victoria-metrics/values.yaml') | from_yaml }}"
    - name: Deploy VictoriaMetrics Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'victoria-metrics/ingress.yaml') | from_yaml }}"
- name: Setup VM - Deletion block
  tags: [ delete ]
  block:
    - name: Delete VictoriaMetrics
      kubernetes.core.helm:
        name: victoria-metrics-single
        chart_ref: "victoria-metrics-single"
        chart_repo_url: https://victoriametrics.github.io/helm-charts/
        release_namespace: default
        release_state: absent
    - name: Delete VictoriaMetrics Ingress
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'victoria-metrics/ingress.yaml') | from_yaml }}"