---
- name: Retrieve values from shub dict
  tags: [ always ]
  hosts: all
  gather_facts: true
  run_once: true

  tasks:
    - name: Get content of shub_config and read it as json
      set_fact:
        shub_config_content: "{{ shub_config | from_json }}"
    - name: Extract checkpoint_interval and window_size from shub_config
      set_fact:
        enable_ipv6: "{{ shub_config_content['platforms.enable_ipv6']  }}"
        tailscale_backend: "{{ shub_config_content['platforms.tailscale_backend'] }}"
        k3s_version: "{{ shub_config_content['scalehub.k3s_version'] }}"
      no_log: true

    - name: Define INSTALL_K3S_EXEC
      set_fact:
        INSTALL_K3S_EXEC: "--data-dir=/tmp/k3s"

    - name: Configure tailscale
      vars:
        tailscale_args: "name=tailscale,joinKey={{ tailscale_auth_key }}"
      set_fact:
        INSTALL_K3S_EXEC: "{{ INSTALL_K3S_EXEC }} --vpn-auth={{ tailscale_args }}"
      no_log: true
      when: tailscale_backend is defined and tailscale_backend == True

- name: Install k3s on control node
  hosts: control
  become: true
  gather_facts: false
  roles:
    - role: k3s_control

- name: Install k3s on worker nodes
  hosts: agents
  become: true
  gather_facts: false
  roles:
    - role: k3s_worker

- name: Run post-install configuration tasks
  hosts: localhost
  gather_facts: false
  roles:
    - role: post_install
