---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiment-monitor
  namespace: experiment-monitor
  labels:
    app: experiment-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: experiment-monitor
  template:
    metadata:
      name: experiment-monitor
      labels:
        app: experiment-monitor
    spec:
      serviceAccountName: experiment-monitor
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

      containers:
        - name: experiment-monitor
          image: ghcr.io/ark-sys/scalehub/monitor:latest
          imagePullPolicy: Always
          env:
            - name: MQTT_BROKER_HOST
              value: "mqtt-broker.experiment-monitor.svc.cluster.local"
            - name: MQTT_BROKER_PORT
              value: "1883"
            - name: MQTT_BROKER_USERNAME
              value: "monitor"
            - name: MQTT_BROKER_PASSWORD
              value: "m_password"
          volumeMounts:
            - mountPath: /experiment-volume
              name: experiment-volume
          ports:
            - containerPort: 1883
              name: mqtt
      restartPolicy: Always
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: experiment-volume
          persistentVolumeClaim:
            claimName: experiments-pvc