---
- name: Setting up MinIO - Creation block
  tags: [ create ]
  block:
    - name: Add chart for local-path-provisioner from containeroo
      kubernetes.core.helm_repository:
        name: containeroo
        repo_url: https://charts.containeroo.ch
        # Install local-path-provisioner with nodePathMap pointing to /tmp/data
    - name: Install local-path-provisioner
      kubernetes.core.helm:
        name: local-path-provisioner
        chart_ref: "containeroo/local-path-provisioner"
        chart_version: 0.0.25
        release_namespace: minio-operator
        create_namespace: true
        release_state: present
        wait: true
        values:
          storageClass:
            create: true
            name: local-path
            defaultClass: true
            allowVolumeExpansion: true
            reclaimPolicy: Delete
            volumeBindingMode: WaitForFirstConsumer
            defaultVolumeType: hostPath
          nodePathMap:
            - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
              paths:
                - /var/local-path-provisioner

    - name: Add MinIo chart
      kubernetes.core.helm_repository:
        name: minio-operator
        repo_url: https://operator.min.io/

    - name: Get count of worker nodes that can host MinIO tenants
      kubernetes.core.k8s_info:
        kind: Node
        label_selectors:
          - node-role.kubernetes.io/tnode=grid5000
      register: num_tenant_nodes

    - name: Fill tenant values with number of nodes
      ansible.builtin.template:
        src: tenant-values.yaml.j2
        dest: /tmp/tenant-values.yaml
        mode: '0644'
      vars:
        num_servers: "{{ num_tenant_nodes.resources | length }}"

    - name: Install MinIO Operator
      kubernetes.core.helm:
        name: minio-operator
        chart_ref: "minio-operator/operator"
        chart_version: 6.0.4
        release_namespace: minio-operator
        create_namespace: true
        release_state: present
        wait: true
        values: "{{ lookup('file', 'minio/operator-values.yaml') | from_yaml }}"

    - name: Deploy MinIO tenant
      kubernetes.core.helm:
        name: minio-tenant
        chart_ref: "minio-operator/tenant"
        chart_version: 6.0.4
        release_namespace: minio-operator
        release_state: present
        wait: true
        values: "{{ lookup('file', '/tmp/tenant-values.yaml') | from_yaml }}"

    - name: Clean tmp/tenant-values.yaml
      ansible.builtin.file:
        path: /tmp/tenant-values.yaml
        state: absent

- name: MinIO - Deletion block
  tags: [ delete ]
  block:
    - name: Delete MinIO tenant
      kubernetes.core.helm:
        name: minio-tenant
        chart_ref: "minio-operator/tenant"
        release_namespace: minio-operator
        release_state: absent
    - name: Delete MinIO Operator
      kubernetes.core.helm:
        name: minio-operator
        chart_ref: "minio-operator/operator"
        release_namespace: minio-operator
        release_state: absent
    - name: Delete MinIO repo
      kubernetes.core.helm_repository:
        name: minio-operator
        repo_url: https://operator.min.io/
        state: absent