apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: flink-taskmanager
  labels:
    app: flink
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9249
  selector:
    app: flink
    component: taskmanager