---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tenant-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp/experiment-data
  # Deploy PV on storage node, labeled node-role.kubernetes.io/scalehub-storage=true
  nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/scalehub-storage
              operator: In
              values:
              - "true"
