---
# Apply grid5000 specific configuration
- name: Apply grid5000 specific configuration
  hosts: G5k
  gather_facts: false
  become: true
  roles:
    - role: grid5000

# Apply vagrant specific configuration
- name: Apply vagrant specific configuration
  hosts: vagrant
  gather_facts: true
  become: true
  roles:
    - role: vagrantg5k

# Apply vmong5k specific configuration
- name: Apply vmong5k specific configuration
  hosts: VMonG5k
  gather_facts: true
  become: true
  roles:
    - role: vmong5k

# Apply picocluster specific configuration
- name: Apply picocluster specific configuration
  hosts: pico
  gather_facts: true
  become: true
  roles:
    - role: picocluster

# Common setup to all nodes
- name: Do common setup for all nodes
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common

