---
# Apply grid5000 specific configuration
- name: Apply grid5000 specific configuration
  hosts: grid5000
  gather_facts: false
  become: true
  roles:
    - role: grid5000

# Apply vm_on_grid5000 specific configuration
- name: Apply vm_on_grid5000 specific configuration
  hosts: vm_grid5000
  gather_facts: true
  become: true
  roles:
    - role: vm_on_grid5000

# Apply picocluster specific configuration
- name: Apply picocluster specific configuration
  hosts: pico
  gather_facts: true
  become: true
  roles:
    - role: picocluster

# Install common packages to all types of nodes
- name: Install common packages
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common
