---
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: fixed-latency-consul
spec:
  selector:
    namespaces:
      - consul
    labelSelectors:
        app: consul
        component: client
    nodeSelectors:
      'node-role.kubernetes.io/worker': 'consumer'
  # All values are described here
  # https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/#field-description
  mode: fixed-percent
  value: '50'
  action: delay
  delay:
    latency: 25ms
    correlation: '0'
    jitter: 0ms
  direction: to
