apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: fluctuating-latencies-consul
  namespace: default
spec:
  entry: fluctuating-latencies-workflow
  templates:
    - name: fluctuating-latencies-workflow
      templateType: Serial
      children:
        - fluctuating-latencies-1
        - fluctuating-latencies-2
        - fluctuating-latencies-3
        - fluctuating-latencies-4
        - fluctuating-latencies-5
    - name: fluctuating-latencies-1
      schedule:
        schedule: '*/5 * * * *'
        type: 'NetworkChaos'
        historyLimit: 1
        concurrencyPolicy: 'Forbid'
      templateType: NetworkChaos
      networkChaos:
        direction: to
        action: delay
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - consul
          labelSelectors:
            'app': 'consul'
            'component': 'client'
          nodeSelectors:
            'node-role.kubernetes.io/worker': 'consumer'
        delay:
          latency: '5ms'
          correlation: '0'
          jitter: '0ms'
        duration: '60s'
    - name: fluctuating-latencies-2
      schedule:
        schedule: '*/5 * * * *'
        type: 'NetworkChaos'
        historyLimit: 1
        concurrencyPolicy: 'Forbid'
      templateType: NetworkChaos
      networkChaos:
        direction: to
        action: delay
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - consul
          labelSelectors:
            'app': 'consul'
            'component': 'client'
          nodeSelectors:
            'node-role.kubernetes.io/worker': 'consumer'
        delay:
          latency: '10ms'
          correlation: '0'
          jitter: '0ms'
        duration: '60s'
    - name: fluctuating-latencies-3
      schedule:
        schedule: '*/5 * * * *'
        type: 'NetworkChaos'
        historyLimit: 1
        concurrencyPolicy: 'Forbid'
      templateType: NetworkChaos
      networkChaos:
        direction: to
        action: delay
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - consul
          labelSelectors:
            'app': 'consul'
            'component': 'client'
          nodeSelectors:
            'node-role.kubernetes.io/worker': 'consumer'
        delay:
          latency: '15ms'
          correlation: '0'
          jitter: '0ms'
        duration: '60s'
    - name: fluctuating-latencies-4
      schedule:
        schedule: '*/5 * * * *'
        type: 'NetworkChaos'
        historyLimit: 1
        concurrencyPolicy: 'Forbid'
      templateType: NetworkChaos
      networkChaos:
        direction: to
        action: delay
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - consul
          labelSelectors:
            'app': 'consul'
            'component': 'client'
          nodeSelectors:
            'node-role.kubernetes.io/worker': 'consumer'
        delay:
          latency: '20ms'
          correlation: '0'
          jitter: '0ms'
        duration: '60s'
    - name: fluctuating-latencies-5
      schedule:
        schedule: '*/5 * * * *'
        type: 'NetworkChaos'
        historyLimit: 1
        concurrencyPolicy: 'Forbid'
      templateType: NetworkChaos
      networkChaos:
        direction: to
        action: delay
        mode: fixed-percent
        value: '50'
        selector:
          namespaces:
            - consul
          labelSelectors:
            'app': 'consul'
            'component': 'client'
          nodeSelectors:
            'node-role.kubernetes.io/worker': 'consumer'
        delay:
          latency: '25ms'
          correlation: '0'
          jitter: '0ms'
        duration: '60s'