---
- name: Deploy experiment-monitor
  tags: [ create ]
  block:
    - name: Create experiment-monitor namespace
      kubernetes.core.k8s:
        name: experiment-monitor
        kind: Namespace
        state: present
    - name: Add truechart helm chart repository
      kubernetes.core.helm_repository:
        name: truecharts
        repo_url: https://charts.truecharts.org/
    - name: Install helm chart for MQTT broker
      kubernetes.core.helm:
      chart_ref: "truecharts/mosquitto"
      release_namespace: experiment-monitor
      create_namespace: true
      release_name: mqtt-broker
      wait: true
      values:
      service:
          type: NodePort
          nodePort: 30001
          port: 1883
          targetPort: 1883
      ingress:
          enabled: true
          annotations: |
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
          hosts:
          - host: mqtt-broker.scalehub.local
            paths:
              - /
          pathType: Prefix
    - name: Deploy experiment-monitor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor.yaml') | from_yaml }}"
- name: Delete experiment-monitor
  tags: [ delete ]
  block:
    - name: Delete experiment-monitor
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor.yaml') | from_yaml }}"
    - name: Delete broker helm release
      kubernetes.core.helm:
        release_name: mqtt-broker
        state: absent
    - name: Delete experiment-monitor namespace
      kubernetes.core.k8s:
        name: experiment-monitor
        kind: Namespace
        state: absent
