---
- name: Deploy experiment-monitor
  tags: [ create ]
  block:
    - name: Create experiment-monitor namespace
      kubernetes.core.k8s:
        name: experiment-monitor
        kind: Namespace
        state: present
    - name: Create PVC for experiment-monitor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiments-pvc.yaml') | from_yaml }}"
    - name: Add t3n chart repository
      kubernetes.core.helm_repository:
        name: t3n
        repo_url: https://storage.googleapis.com/t3n-helm-charts
    - name: Install mosquitto broker
      kubernetes.core.helm:
        release_name: mqtt-broker
        release_namespace: experiment-monitor
        release_state: present
        chart_ref: t3n/mosquitto
        wait: true
        values:
          persistence:
            enabled: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: "true"
          service:
            type: NodePort
          ports:
            mqtt:
              port: 1883
              nodePort: 30001
            websocket:
              port: 9001
              nodePort: 30002
          config: |
            persistence true
            persistence_location /mosquitto/data/
            log_dest stdout
            listener 1883
            listener 9001
            allow_anonymous true
    - name: Copy gitlab-scalehub secret from default namespace to experiment-monitor namespace
      block:
        - name : Get gitlab-scalehub secret from default namespace
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Secret
            name: gitlab-scalehub
            namespace: default
          register: gitlab_scalehub_secret
        - name: Create gitlab-scalehub secret in experiment-monitor namespace
          kubernetes.core.k8s:
              state: present
              definition:
                apiVersion: v1
                kind: Secret
                metadata:
                    name: gitlab-scalehub
                    namespace: experiment-monitor
                type: kubernetes.io/dockerconfigjson
                data:
                    .dockerconfigjson: "{{ gitlab_scalehub_secret.resources[0].data['.dockerconfigjson'] }}"
    - name: Copy kubeconfig secret from default namespace to experiment-monitor namespace
      block:
        - name : Get kubeconfig secret from default namespace
          kubernetes.core.k8s_info:
            api_version: v1
            kind: Secret
            name: kube-secret
            namespace: default
          register: kubeconfig_secret
        - name: Create kubeconfig secret in experiment-monitor namespace
          kubernetes.core.k8s:
              state: present
              definition:
                apiVersion: v1
                kind: Secret
                metadata:
                    name: kube-secret
                    namespace: experiment-monitor
                type: Opaque
                data:
                    kubeconfig: "{{ kubeconfig_secret.resources[0].data['kubeconfig'] }}"
    - name: Deploy experiment-monitor
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiment-monitor.yaml') | from_yaml }}"
- name: Delete experiment-monitor
  tags: [ delete ]
  block:
    - name: Delete experiment-monitor
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'experiment-monitor/experiment-monitor.yaml') | from_yaml }}"
    - name: Delete broker helm release
      kubernetes.core.helm:
        release_name: mqtt-broker
        release_namespace: experiment-monitor
        state: absent
    - name: Delete secrets
      block:
        - name: Delete kube-secret
          kubernetes.core.k8s:
            name: kube-secret
            kind: Secret
            namespace: experiment-monitor
            state: absent
        - name: Delete gitlab-scalehub secret
          kubernetes.core.k8s:
            name: gitlab-scalehub
            kind: Secret
            namespace: experiment-monitor
            state: absent
    - name: Delete PVC
      kubernetes.core.k8s:
          name: experiments-pvc
          kind: PersistentVolumeClaim
          namespace: experiment-monitor
          state: absent
    - name: Delete experiment-monitor namespace
      kubernetes.core.k8s:
        name: experiment-monitor
        kind: Namespace
        state: absent
