# Setup task for Prometheus
- name: Setup Prometheus - Creation block
  delegate_to: localhost
  tags: [ create ]
  block:
    - name: Deploy latest version of Prometheus Stack in monitoring namespace
      kubernetes.core.helm:
        chart_ref: "kube-prometheus-stack"
        chart_version: 51.9.0
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        release_namespace: monitoring
        create_namespace: true
        release_name: prometheus
        values: "{{ lookup('ansible.builtin.file', 'kube-prometheus-stack-values.yaml') | from_yaml }}"

    - name: Deploying Flink rules
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'flinkrules.yaml') | from_yaml }}"
