---
- name: Setting up MinIO - Creation block
  tags: [create]
  delegate_to: localhost
  block:
    - name: Deploy PV for MinIO
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'tenant-pv.yaml') | from_yaml }}"
    - name: Add MinIo chart
      kubernetes.core.helm_repository:
        name: minio-operator
        repo_url: https://operator.min.io/
    - name: Install MinIO Operator
      kubernetes.core.helm:
        name: minio-operator
        chart_ref: "minio-operator/operator"
        chart_version: 5.0.10
        release_namespace: minio-operator
        create_namespace: true
        release_state: present
        wait: true
        values:
          operator:
            nodeSelector:
              node-role.kubernetes.io/scalehub-storage: "true"
          console:
            enabled: true
            env:
              - name: MINIO_BROWSER
                value: "on"
              - name: MINIO_SERVER_URL
                value: "http://minio.scalehub.local"
              - name: MINIO_REDIRECT_URL
                value: "http://minio-console.scalehub.local"
              - name: MINIO_PROMETHEUS_URL
                value : "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local"
            nodeSelector:
              node-role.kubernetes.io/scalehub-storage: "true"
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: name
                          operator: In
                          values:
                            - minio-operator
                    topologyKey: kubernetes.io/hostname
            ingress:
              enabled: true
              ingressClassName: nginx
              host: minio-console.scalehub.local
              path: /
              pathType: Prefix
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/rewrite-target: /
    - name: Deploy MinIO tenant
      kubernetes.core.helm:
        name: minio-tenant
        chart_ref: "minio-operator/tenant"
        chart_version: 5.0.10
        release_namespace: minio-operator
        release_state: present
        wait: true
        values:
          tenant:
            # Disable TLS
            certificate:
              requestAutoCert: false
            name: scalehub-tenant
            replicas: 1
            prometheusOperator: true
            pools:
              - servers: 1
                volumesPerServer: 1
                name: flink-pool
                size: 50Gi
                storageClassName: local-storage
            nodeSelector:
              node-role.kubernetes.io/scalehub-storage: "true"
            buckets:
              - name: flink-bucket
                policy: public
                objectLocking: false
          ingress:
            console:
              enabled: true
              host: minio-tenant.scalehub.local
              path: /
              pathType: Prefix
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/rewrite-target: /

- name: MinIO - Deletion block
  tags: [delete]
  delegate_to: localhost
  block:
    - name: Delete MinIO tenant
      kubernetes.core.helm:
        name: minio-tenant
        chart_ref: "minio-operator/tenant"
        release_namespace: minio-operator
        release_state: absent
    - name: Delete MinIO Operator
      kubernetes.core.helm:
        name: minio-operator
        chart_ref: "minio-operator/operator"
        release_namespace: minio-operator
        release_state: absent
    - name: Delete MinIO repo
      kubernetes.core.helm_repository:
        name: minio-operator
        repo_url: https://operator.min.io/
        state: absent
    - name: Delete PV for MinIO
      kubernetes.core.k8s:
          state: absent
          definition: "{{ lookup('ansible.builtin.file', 'tenant-pv.yaml') | from_yaml }}"