---
# Setup PVC
- name: Setting up PrivateVolumeClaims - Creation block
  tags: [ create ]
  delegate_to: localhost
  block:
    - name: Deploy PVC for Grafana
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'pvc/grafana-pvc.yaml') | from_yaml }}"

    - name: Deploy PVC for VictoriaMetrics
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'pvc/vm-pvc.yaml') | from_yaml }}"

    - name: Deploy PVC for .jar artifacts
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'pvc/artifacts-pvc.yaml') | from_yaml }}"
    - name: Deploy PVC for experiments
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'pvc/experiments-pvc.yaml') | from_yaml }}"

- name: Setting up PrivateVolumeClaims - Deletion block
  tags: [ delete ]
  delegate_to: localhost
  block:
    - name: Delete PVC for Grafana
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'pvc/grafana-pvc.yaml') | from_yaml }}"

    - name: Delete PVC for .jar artifacts
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'pvc/artifacts-pvc.yaml') | from_yaml }}"

    - name: Delete PVC for VictoriaMetrics
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'pvc/vm-pvc.yaml') | from_yaml }}"

    - name: Delete PVC for experiments
      kubernetes.core.k8s:
          state: absent
          definition: "{{ lookup('ansible.builtin.file', 'pvc/experiments-pvc.yaml') | from_yaml }}"