- name: Install Vagrant
  tags: [ create ]
  become: true
  block:
    - name: Download binary
      ansible.builtin.get_url:
        url: https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3_linux_amd64.zip
        dest: /tmp/vagrant.zip

    - name: Unzip binary
      ansible.builtin.unarchive:
        src: /tmp/vagrant.zip
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/vagrant

    - name: Install libvirt plugin
      ansible.builtin.command:
        cmd: vagrant plugin install vagrant-libvirt
#    - name: set user
#      set_fact:
#        ansible_user: karsalane
#
#    - name: Generate Vagrantfile from template
#      ansible.builtin.template:
#        scalehub: Vagrantfile.j2
#        dest: /home/{{ ansible_user }}/Vagrantfile
#        owner: "{{ ansible_user }}"
#        group: "g5k-users"
#        mode: '0644'
#
#    - name: Start VMs using Vagrant
#      ansible.builtin.command:
#        cmd: vagrant up
#        chdir: /home/{{ ansible_user }}
#      register: vagrant_up_result
#      changed_when: "'running' in vagrant_up_result.stdout"


#- name: Remove Vagrant Vms
#  tags: [ delete ]
#  become: true
#  ansible.builtin.command:
#    cmd: vagrant destroy -f
#    args:
#      chdir: /home/{{ ansible_user }}
#  ignore_errors: yes