---
- name: Deploy Kafka stack
  tags: [ create ]
  block:
    - name: Clean /tmp/experiment-data/kafka on producer nodes
      command: "rm -rf /tmp/experiment-data/kafka"
      delegate_to: "{{ item }}"
      become: true
      with_items: "{{ groups['producers'] }}"
      when: groups['producers'] | length > 0

    - name: Deploy Schema-registry service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'schema-registry/schema-registry-service.yaml' ) | from_yaml }}"

    - name: Deploy Zookeper service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'zookeeper/zookeeper-service.yaml' ) | from_yaml }}"

    - name: Deploy Kafka services
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', item) | from_yaml }}"
      with_fileglob: [ "kafka/*.yaml" ]

    - name: Deploy Schema-registry
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'schema-registry/schema-registry-deployment.yaml.j2') | from_yaml }}"

    - name: Deploy Zookeeper
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'zookeeper/zookeeper-deployment.yaml.j2' ) | from_yaml }}"


    - name: Deploy Kafka
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'kafka/kafka-deployment.yaml.j2' ) | from_yaml }}"

- name: Delete Kafka stack
  tags: [ delete ]
  block:
    - name: Delete Schema-registry service
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'schema-registry/schema-registry-service.yaml' ) | from_yaml }}"

    - name: Delete Zookeper service
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'zookeeper/zookeeper-service.yaml' ) | from_yaml }}"

    - name: Delete Kafka services
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', item) | from_yaml }}"
      with_fileglob: [ "kafka/*.yaml" ]

    - name: Delete Schema-registry
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'schema-registry/schema-registry-deployment.yaml.j2') | from_yaml }}"

    - name: Delete Zookeeper
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'zookeeper/zookeeper-deployment.yaml.j2' ) | from_yaml }}"


    - name: Delete Kafka
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'kafka/kafka-deployment.yaml.j2' ) | from_yaml }}"




