---
- name: Deploy Flink
  hosts: localhost
  gather_facts: false
  roles:
    - role: flink
      when: not template_deployment | default(false)

- name: Deploy template Flink job
  hosts: localhost
  tasks:
    - import_tasks: roles/flink/tasks/template.yaml
      when: template_deployment | default(false)
  vars:
    image: flink
    tag: 1.20.3-java11