---
- name: Deploy Flink
  hosts: localhost
  gather_facts: false
  roles:
    - flink
  when: not template_deployment | default(false)

- name: Deploy template Flink job
  include_tasks: tasks/template.yaml
  when: template_deployment