apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
  clusterIP: None
  selector:
    app: zookeeper
