---
- name: Common config
  tags: [ create ]
  block:
    - name: Deploy secret gitlab access for transscale
      kubernetes.core.k8s:
        state: present
        force: yes
        definition: "{{ lookup('ansible.builtin.file', 'gitlab-registry.yaml') | from_yaml }}"
    - name: Get kubeconfig from cluster
      shell: kubectl config view --raw --minify
      register: kubeconfig
    - name: Create Secret with kubeconfig for transscale
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: transscale-secret
            namespace: default
          data:
            kubeconfig: "{{ kubeconfig.stdout | b64encode }}"
- import_tasks: transscale.yaml
