---
- name: Common config
  tags: [ create ]
  block:
    - name: Deploy secret gitlab access for transscale
      kubernetes.core.k8s:
        state: present
        force: yes
        definition: "{{ lookup('ansible.builtin.file', 'gitlab-registry.yaml') | from_yaml }}"

- import_tasks: consul.yaml

- import_tasks: transscale.yaml

#- name: Deploy Serf
#  tags: [ create ]
#  block:
#    - name: Add whereabouts chart repository
#      kubernetes.core.helm_repository:
#        name: bitnami
#        repo_url: https://charts.bitnami.com/bitnami
#
#    - name: Install whereabouts plugin
#      kubernetes.core.helm:
#        chart_ref: "bitnami/whereabouts"
#        release_namespace: whereabouts
#        create_namespace: true
#        release_name: whereabouts
#
#    - name: Create new Network Attachment Definition for the serf deamonset
#      kubernetes.core.k8s:
#        state: present
#        definition: "{{ lookup('ansible.builtin.file', 'serf-network.yaml') | from_yaml }}"
#
#    - name: Deploy serf service
#      kubernetes.core.k8s:
#        state: present
#        definition: "{{ lookup('ansible.builtin.file', 'serf-service.yaml') | from_yaml }}"
#
#    - name: Deploy serf agent on consumer nodes
#      kubernetes.core.k8s:
#        state: present
#        definition: "{{ lookup('ansible.builtin.template', 'serf-agent.yaml.j2') | from_yaml }}"

#- name: Delete serf
#  tags: [ delete ]
#  block:
#    - name: Delete new Network Attachment Definition for the serf deamonset
#      kubernetes.core.k8s:
#        state: absent
#        definition: "{{ lookup('ansible.builtin.file', 'serf-network.yaml') | from_yaml }}"
#
#    - name: Delete serf service
#      kubernetes.core.k8s:
#        state: absent
#        definition: "{{ lookup('ansible.builtin.file', 'serf-service.yaml') | from_yaml }}"
#
#    - name: Delete serf agent on consumer nodes
#      kubernetes.core.k8s:
#        state: absent
#        definition: "{{ lookup('ansible.builtin.template', 'serf-agent.yaml.j2') | from_yaml }}"

