---
- name: Common config
  tags: [ create ]
  block:
    - name: Deploy secret gitlab access for transscale
      kubernetes.core.k8s:
        state: present
        force: yes
        definition: "{{ lookup('ansible.builtin.file', 'gitlab-registry.yaml') | from_yaml }}"

- import_tasks: transscale.yaml
