---
- name: Deploy transscale
  tags: [ create ]
  block:
    - name: Get kubeconfig from cluster
      shell: kubectl config view --raw --minify
      register: kubeconfig

    - name: Create Secret with kubeconfig for transscale
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: transscale-secret
            namespace: default
          data:
            kubeconfig: "{{ kubeconfig.stdout | b64encode }}"

    - name: Deploy secret gitlab access for transscale
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'gitlab-registry.yaml') | from_yaml }}"

    - name: Deploy config file for transscale
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'transscale-config.yaml.j2') | from_yaml }}"
#
#    - name: Deploy transscale
#      kubernetes.core.k8s:
#        state: present
#        definition: "{{ lookup('ansible.builtin.template', 'transscale-deployment.yaml.j2') | from_yaml }}"

    - name: Deploy transscale
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'transscale-job.yaml.j2') | from_yaml }}"
        wait: true
        #TODO  Maybe there is a better way to handle wait timeout
        wait_timeout: 18000
        wait_sleep: 60
        wait_condition:
          type: Complete
          status: "True"


- name: Delete transscale
  tags: [ delete ]
  block:
#    - name: Delete transscale
#      kubernetes.core.k8s:
#        state: absent
#        definition: "{{ lookup('ansible.builtin.template', 'transscale-deployment.yaml.j2') | from_yaml }}"
    - name: Delete transscale
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'transscale-job.yaml.j2') | from_yaml }}"

    - name: Delete transscale configmap
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'transscale-config.yaml.j2') | from_yaml }}"

    - name: Delete secret gitlab access for transscale
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'gitlab-registry.yaml') | from_yaml }}"



