---
- name: Deploy transscale
  tags: [ create ]
  block:
    - name: Get kubeconfig from cluster
      shell: kubectl config view --raw --minify
      register: kubeconfig

    - name: Create Secret with kubeconfig for transscale
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: transscale-secret
            namespace: default
          data:
            kubeconfig: "{{ kubeconfig.stdout | b64encode }}"

    - name: Deploy secret gitlab access for transscale
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'gitlab-registry.yaml') | from_yaml }}"

    - name: Deploy config file for transscale
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'transscale-config.yaml') | from_yaml }}"

    - name: Deploy transscale
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'transscale-deployment.yaml') | from_yaml }}"

- name: Delete transscale
  tags: [ delete ]
  block:
    - name: Delete transscale
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'transscale-deployment.yaml') | from_yaml }}"

    - name: Delete transscale configmap
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'transscale-config.yaml') | from_yaml }}"

    - name: Delete secret gitlab access for transscale
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'gitlab-registry.yaml') | from_yaml }}"



