- name: Deploy transscale
  tags: [ create ]
  block:
    - name: Deploy config file for transscale
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', 'transscale-config.yaml.j2') | from_yaml }}"

    - name: Deploy transscale-job definition
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.file', 'transscale-job-definition.yaml') | from_yaml }}"

- name: Delete transscale
  tags: [ delete ]
  block:
    - name: Delete transscale
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'transscale-job.yaml.j2') | from_yaml }}"

    - name: Delete transscale configmap
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.template', 'transscale-config.yaml.j2') | from_yaml }}"

    - name: Delete transscale-job definition
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('ansible.builtin.file', 'transscale-job-definition.yaml') | from_yaml }}"