apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: flink
  labels:
    app: flink
  name: flink
spec:
  selector:
    matchLabels:
      app: flink
  endpoints:
    - port: metrics
      interval: 5s
