version: "3.6"

secrets:
  creds:
    # Fill this file with personal Grid5000 credentials
    file: secrets/Grid5000_creds.yaml
    # Setup correct path for grid5000 private key in `source` field
  ssh_key:
    file: secrets/grid5000

networks:
  scalehub_net:

services:
  scalehub:
    container_name: scalehub
    depends_on:
      - vpn
    # Use network stack from vpn service
    network_mode: service:vpn
    secrets:
      - source: creds
        target: /root/.python-grid5000.yaml
      - source: ssh_key
        target: /root/.ssh/id_rsa
        mode: 600
    build:
      context: .
      dockerfile: Dockerfile
    # Source paths refer to scalehub root path
    volumes:
      - type: bind
        source: ../conf
        target: /app/conf
      - type: bind
        source: ../playbooks
        target: /app/playbooks
      - type: bind
        source: ../script
        target: /app/script
      - type: bind
        source: ../experiments-data
        target: /app/experiments-data
  vpn:
    image: dperson/openvpn-client
    # cap_add, security_opt, and volume required for the image to function
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - scalehub_net
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./secrets:/vpn
    environment:
      - DNS
      - TZ=Europe/Paris
    command:
      - -D
    # Option description of -D : Don't use the connection as the default route -> don't break ssh connections from scalehub to g5k
