# Create a ci/cd pipeline for experiment-monitor to build and push the image to the registry

image: docker:latest
stages:
  - build-and-push

before_script:
  # login to the registry
  - echo -n $CI_REGISTRY_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  # Install git
  - apk add --update git
build-and-push:
  # build and push the image to the registry
  stage: build-and-push
  tags:
    - ci.inria.fr
    - large
  script:
    # build the image
    - docker build -t "$CI_REGISTRY/$CI_REGISTRY_PROJECT/experiment-monitor" .
    # push the image to the registry
    - docker push "$CI_REGISTRY/$CI_REGISTRY_PROJECT/experiment-monitor"

