---
#- name: Add kafka/strimzi chart
#  vars:
#     helm_chart_url: "https://strimzi.io/charts/"
#  kubernetes.core.helm_repository:
#    name: strimzi-operator
#    repo_url: "{{ helm_chart_url }}"
#
#- name: Install kafka/strimzi chart
#  kubernetes.core.helm:
#    name: strimzi-operator
#    namespace: default
#    chart_ref: strimzi/strimzi-kafka-operator
#
#- name: Add prometheus chart
#  vars:
#     helm_chart_url: "https://prometheus-community.github.io/helm-charts"
#  kubernetes.core.helm_repository:
#    name: prometheus-community
#    repo_url: "{{ helm_chart_url }}"
#
#- name: Install prometheus chart
#  kubernetes.core.helm:
#    name: prometheus-community
#    namespace: monitoring
#    chart_ref: prometheus-community/kube-prometheus-stack

# vim: set ft=yaml:
- name: Deploy Zookeeper
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
  with_fileglob:
    - "../templates/zookeeper/*.yaml"

- name: Setup and deploy Kafka
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
  with_fileglob:
    - "../templates/kafka/*.yaml"

- name: Deploy Flink
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
  with_fileglob:
    - "../templates/flink/*.yaml"

#- name: Deploy Prometheus ServiceMonitor for jobmanager and taskmanager
#  kubernetes.core.k8s:
#    state: present
#    definition: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
#  with_fileglob:
#    - "../templates/prometheus/*.yaml"