# Create a ci/cd pipeline for experiment-monitor to build and push the image to the registry
image: docker:latest
stages:
  - build
  - push

before_script:
  # login to the registry
  - echo -n $CI_REGISTRY_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  # build and push the image to the registry
  stage: build
  tags:
    - ci.inria.fr
    - small
  script:
    # build the image of experiment-monitor context
    - docker build -t "$CI_REGISTRY/$CI_REGISTRY_PROJECT/scalehub/monitor" -f setup/monitor/Dockerfile .

push:
  stage: push
  tags:
    - ci.inria.fr
    - small
  script:
    - echo "Pushing the image to the registry"
    # push the image to the registry
    - docker push "$CI_REGISTRY/$CI_REGISTRY_PROJECT/scalehub/monitor"
  needs:
    - job: build
