# Create a ci/cd pipeline for experiment-monitor to build and push the image to the registry
image: docker:27.3

stages:
  - work

before_script:
  # login to the registry
  - echo -n $CI_REGISTRY_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build-and-push:
  # build and push the image to the registry
  stage: work
  tags:
    - ci.inria.fr
    - small
  script:
    # build the image for experiment-monitor using current context
    - docker build -t "$CI_REGISTRY/$CI_REGISTRY_PROJECT/scalehub/monitor" -f setup/monitor/Dockerfile .
    # Create artifact
    - echo "Creating artifact"
    - docker push "$CI_REGISTRY/$CI_REGISTRY_PROJECT/scalehub/monitor"
