Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define "vm-paradoxe-32-1" do |vm_config|
        vm_config.vm.box = "debian/stretch64"
        vm_config.vm.hostname = "vm-paradoxe-32-1"
        vm_config.ssh.username = "vagrant"

        vm_config.vm.provider "libvirt" do |libvirt|
          libvirt.memory = 32000
          libvirt.cpus = 8
          libvirt.nic_model_type = "virtio"
          libvirt.domain_name = "vm-paradoxe-32-1"
        end

        vm_config.vm.network "private_network", ip: "192.168.100.2"

        vm_config.vm.network "public_network", dev: "br-ovs", mode: "bridge", type: "bridge"

        end
    config.vm.define "vm-paradoxe-32-2" do |vm_config|
        vm_config.vm.box = "debian/stretch64"
        vm_config.vm.hostname = "vm-paradoxe-32-2"
        vm_config.ssh.username = "vagrant"

        vm_config.vm.provider "libvirt" do |libvirt|
          libvirt.memory = 32000
          libvirt.cpus = 8
          libvirt.nic_model_type = "virtio"
          libvirt.domain_name = "vm-paradoxe-32-2"
        end

        vm_config.vm.network "private_network", ip: "192.168.100.3"
        vm_config.vm.network "public_network", dev: "br-ovs", mode: "bridge", type: "bridge"

        end
  end