---
# Setup cert-manager
- name: Setting up cert-manager
  tags: [ create ]
  block:
    - name: Add cert-manager repo
      kubernetes.core.helm_repository:
        name: cert-manager
        repo_url: https://charts.jetstack.io
        state: present

    - name: Install cert-manager
      kubernetes.core.helm:
        chart_ref: cert-manager/cert-manager
        name: cert-manager
        release_namespace: cert-manager
        create_namespace: true
        wait: true
        release_state: present
        values: "{{ lookup('file', 'cert-manager/values.yaml' ) | from_yaml}}"

    - name: Create Issuer
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'cert-manager/issuer.yaml') }}"
        state: present

    - name: Create CA Certificate
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'cert-manager/ca-cert.yaml') }}"
        state: present

    - name: Create Certificate
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'cert-manager/cert.yaml') }}"
        state: present

- name: Delete cert-manager
  tags: [ delete ]
  block:
    - name: Delete cert-manager
      kubernetes.core.helm:
        chart_ref: cert-manager/cert-manager
        name: cert-manager
        release_namespace: cert-manager
        release_state: absent

    # Delete Issuer
    - name: Delete Issuer
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'cert-manager/issuer.yaml') }}"
        state: absent

    # Delete CA Certificate
    - name: Delete CA Certificate
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'cert-manager/ca-cert.yaml') }}"
        state: absent

    # Delete Certificate
    - name: Delete Certificate
      kubernetes.core.k8s:
        definition: "{{ lookup('file', 'cert-manager/cert.yaml') }}"
        state: absent
