---
# Setup Ingress
- name: Setting up Ingress
  tags: [ create ]
  delegate_to: localhost
  block:
    - name: Add Ingress repo
      kubernetes.core.helm_repository:
          name: ingress-nginx
          repo_url: https://kubernetes.github.io/ingress-nginx
          state: present
    - name: Install Ingress
      kubernetes.core.helm:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        chart_ref: ingress-nginx/ingress-nginx
        name: ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        wait: true
        release_state: present
        values: "{{ lookup('file', 'values.yaml' ) | from_yaml}}"

    - name: Get cluster info
      kubernetes.core.k8s_cluster_info:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
      register: cluster_info

    - name: Retrieve IP address from host url (connection.host from cluster_info returns the url. extract IP address)
      set_fact:
        ingress_ip: "{{ cluster_info.connection.host | regex_replace('https://', '') | regex_replace(':6443', '') }}"

    - name: Update ingress-upstream.k3s.scalehub.dev entry in /etc/hosts with the IP address
      lineinfile:
        path: /etc/hosts
        regexp: '^.*ingress-upstream\.k3s\.scalehub\.dev.*$'
        line: "{{ ingress_ip }} ingress-upstream.k3s.scalehub.dev"
        state: present

#    - name: Perform nginx reload on reverse-proxy container
#      command: docker exec -it nginx_reverse nginx -s reload
#      ignore_errors: yes

- name: Delete Ingress
  tags: [ delete ]
  delegate_to: localhost
  kubernetes.core.helm:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
    chart_ref: ingress-nginx/ingress-nginx
    name: ingress-nginx
    release_namespace: ingress-nginx
    release_state: absent
