---
- name: Post-install configuration
  tags: [ create ]
  block:
    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: present

    - name: Create flink namespace
      kubernetes.core.k8s:
        name: flink
        api_version: v1
        kind: Namespace
        state: present

    - name: Create kafka namespace
      kubernetes.core.k8s:
        name: kafka
        api_version: v1
        kind: Namespace
        state: present

    - name: Create experiment-monitor namespace
      kubernetes.core.k8s:
        name: experiment-monitor
        api_version: v1
        kind: Namespace
        state: present

- name: Remove namespaces
  tags: [ delete ]
  block:
    - name: Delete monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        api_version: v1
        kind: Namespace
        state: absent

    - name: Delete flink namespace
      kubernetes.core.k8s:
        name: flink
        api_version: v1
        kind: Namespace
        state: absent

    - name: Delete kafka namespace
      kubernetes.core.k8s:
        name: kafka
        api_version: v1
        kind: Namespace
        state: absent

    - name: Delete experiment-monitor namespace
      kubernetes.core.k8s:
        name: experiment-monitor
        api_version: v1
        kind: Namespace
        state: absent