---
# Setup Ingress
- name: Setting up Ingress
  tags: [ create ]
  delegate_to: localhost
  block:
    - name: Add Ingress repo
      kubernetes.core.helm_repository:
          name: ingress-nginx
          repo_url: https://kubernetes.github.io/ingress-nginx
          state: present
    - name: Install Ingress
      kubernetes.core.helm:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        chart_ref: ingress-nginx/ingress-nginx
        name: ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        wait: true
        release_state: present
    - name: Save ingress controller IP
      set_fact:
        ingress_ip: "{{ lookup('pipe', 'kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath={.status.loadBalancer.ingress[0].ip}') }}"
    - name: Update /etc/hosts with ingress IP
      become: true
      ansible.builtin.shell: awk -v domain="ingress.scalehub.local" -v new_ip="{{ ingress_ip }}" '$2 == domain {$1 = new_ip; found = 1} {print $0} END {if (found != 1) print new_ip, domain}' /etc/hosts | tee /etc/hosts > /dev/null
    - name: Trigger nginx reload on scalehub container
      become: true
      ansible.builtin.shell: nginx -s reload
    - name: Deploy ingress for Flink
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition: "{{ lookup('ansible.builtin.file', 'flink-ingress.yaml') | from_yaml }}"

- name: Ingress - Deletion block
  tags: [ delete ]
  delegate_to: localhost
  block:
    - name: Delete Ingress repo
      kubernetes.core.helm_repository:
          name: ingress-nginx
          repo_url: https://kubernetes.github.io/ingress-nginx
          state: absent
    - name: Delete Ingress for Flink
      kubernetes.core.k8s:
        state: absent
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition: "{{ lookup('ansible.builtin.file', 'flink-ingress.yaml') | from_yaml }}"