- name: Add secrets to access resources
  tags: [ create ]
  vars:
    api_url: "https://vault.bitwarden.eu/api"
    identity_url: "https://vault.bitwarden.eu/identity"
    base_url: "https://vault.bitwarden.eu"

    secret_id: "27906bdf-0c6a-44b4-a8eb-b1d100cee2ba"
    access_token: "0.7243b14c-c06a-44be-bce6-b1d100cfeca1.A4zUP09cDsRRGldFUYlsUAB9Zk8QGd:Ew5kaEhn3SAiDgkhMVzDmw=="
    organization_id: "985abad4-c16c-4766-b2f0-b1ca011fca5b"

    pull_token: "{{ lookup('bitwarden.secrets.lookup', secret_id, base_url=base_url, access_token=access_token, organization_id=organization_id) }}"
  #    pull_token: "ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuaW5yaWEuZnIiOiB7CgkJCSJhdXRoIjogImFXMWhaMlZmY0hWc2JHVnlPbWRzY0dGMExYbE1ZbG8zTW0xMWNHNDFjbUUxWWpoRlRYVjAiCgkJfQoJfQp9Cg=="
  block:
    - name: Create Secret to pull images from private registry
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: gitlab-scalehub
            namespace: default
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ pull_token }}"

    - name: Add gitlab-scalehub secret to kafka namespace
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: gitlab-scalehub
            namespace: kafka
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ pull_token }}"

    - name: Add gitlab-scalehub secret to flink namespace
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: gitlab-scalehub
            namespace: flink
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ pull_token }}"
            
    - name: Create Secret with kubeconfig in default namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: kube-secret
            namespace: default
          data:
            kubeconfig: "{{ lookup('file', lookup('env', 'KUBECONFIG')) | b64encode }}"