- name: Add secrets to access resources
  tags: [ create ]
  block:
    - name: Create Secret to pull images from private registry
      vars:
        pull_token: "{{ lookup('bitwarden.secrets.lookup', '27906bdf-0c6a-44b4-a8eb-b1d100cee2ba',base_url='https://vault.bitwarden.eu', api_url='https://vault.bitwarden.eu/api',
        identity_url='https://vault.bitwarden.eu/identity', access_token='0.7243b14c-c06a-44be-bce6-b1d100cfeca1.A4zUP09cDsRRGldFUYlsUAB9Zk8QGd:Ew5kaEhn3SAiDgkhMVzDmw==' ) }}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: gitlab-scalehub
            namespace: default
          type: kubernetes.io/dockerconfigjson
          data:
            .dockerconfigjson: "{{ pull_token }}"
            
    - name: Create Secret with kubeconfig in default namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: kube-secret
            namespace: default
          data:
            kubeconfig: "{{ lookup('file', lookup('env', 'KUBECONFIG')) | b64encode }}"